force-app/main/default/objects/AccountSettings__c/AccountSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Account</description>
    <label>Account Settings</label>
</CustomObject>

force-app/main/default/objects/AccountSettings__c/fields/TRG_SendMailOnMatch__c.field-meta.xml
<CustomField>
    <fullName>TRG_SendMailOnMatch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to switch on/off sending mail on name matching.</description>
    <label>TRG_SendMailOnMatch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
/*---------------------------------------------------------------
Description :            Trigger Handler for Account
Test Class :             AccountTriggerTest
-----------------------------------------------------------------*/
public class AccountTriggerHandler extends TriggerHandler {
    private Map<Id, Account> newAccountMap;
    private Map<Id, Account> oldAccountMap;

    private List<Account> newAccountList;
    private List<Account> oldAccountList;

    public AccountTriggerHandler() {
        this.newAccountList = (List<Account>) Trigger.new;
        this.oldAccountList = (List<Account>) Trigger.old; 
        this.newAccountMap  = (Map<Id, Account>) Trigger.newMap;
        this.oldAccountMap  = (Map<Id, Account>) Trigger.oldMap;
    }

    public override void afterInsert() {
        if(AccountSettings__c.getInstance().TRG_SendMailOnMatch__c) {
            AccountTriggerService.sendMail(newAccountList);
        }
    }

    public override void afterUpdate() {
        if(AccountSettings__c.getInstance().TRG_SendMailOnMatch__c) {
            AccountTriggerService.sendMail(newAccountList);
        }
    }


}