force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email for the account</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/AccountSettings__c/AccountSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Account</description>
    <label>Account Settings</label>
</CustomObject>

force-app/main/default/objects/AccountSettings__c/fields/MailGunApiKey__c.field-meta.xml
<CustomField>
    <fullName>MailGunApiKey__c</fullName>
    <description>API Key for Mail Gun Integration</description>
    <label>MailGun Api Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSettings__c/fields/MailGunSenderEmail__c.field-meta.xml
<CustomField>
    <fullName>MailGunSenderEmail__c</fullName>
    <description>Sender Email used for Mail Gun emails</description>
    <label>MailGun Sender Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSettings__c/fields/RegexForSendingMail__c.field-meta.xml
<CustomField>
    <fullName>RegexForSendingMail__c</fullName>
    <description>Regex for matching Account Name to send mail.</description>
    <label>Regex For Sending Mail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSettings__c/fields/TRG_SendMailOnMatch__c.field-meta.xml
<CustomField>
    <fullName>TRG_SendMailOnMatch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to switch on/off sending mail on name matching.</description>
    <label>TRG_SendMailOnMatch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ExceptionLog__c/ExceptionLog__c.object-meta.xml
<CustomObject>
    <description>Object used to log any excpetions</description>
    <label>ExceptionLog</label>
    <nameField>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExcpetionLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountTriggerTest.cls
/*---------------------------------------------------------------
Description :            Test class for Account Trigger and Mailgun service
Test Class :             N/A
-----------------------------------------------------------------*/
@IsTest
public class AccountTriggerTest {
    
    @TestSetup
    static void setup(){
        AccountSettings__c accountSettings = new AccountSettings__c();

        accountSettings.TRG_SendMailOnMatch__c = true;
        accountSettings.MailGunApiKey__c       = '';
        accountSettings.RegexForSendingMail__c = '.*';
        accountSettings.MailGunSenderEmail__c  = 'someEmail';

        insert accountSettings;
    }

    @IsTest
    public static void testAccountTriggerWithSuccess() {
        Account account = new Account( Name     = 'Test Name',
                                       Email__c = 'test@test12323.com'  );

        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(true));

        Test.startTest();
        insert account;
        Test.stopTest();

        List<ExceptionLog__c> exceptionLog = [SELECT Id, Name FROM ExceptionLog__c];
        System.assertEquals(0, exceptionLog.size());
    }

    @IsTest
    public static void testAccountTriggerWithErrorCode() {
        Account account = new Account( Name     = 'Test Name',
                                       Email__c = 'test@test12323.com'  );

        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(false));

        Test.startTest();
        insert account;
        Test.stopTest();

        List<ExceptionLog__c> exceptionLog = [SELECT Id, Name FROM ExceptionLog__c];
        System.assertNotEquals(0, exceptionLog.size());
    }

    @IsTest
    public static void testAccountTriggerWithNonMatchingName() {
        AccountSettings__c accountSettings = [SELECT Id, RegexForSendingMail__c FROM AccountSettings__c];
        
        accountSettings.RegexForSendingMail__c = '\\bTest[0-9]\\b';

        update accountSettings;

        Account account = new Account( Name     = 'Test Name',
                                       Email__c = 'test@test12323.com'  );

        //If the mock response is called it will throw an assertion error. 
        //Expectation is regex wont match name and thus no callout should be made
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(true, false));

        Test.startTest();
        insert account;
        Test.stopTest();
    }

    @IsTest
    public static void testAccountTriggerWithUpdate() {
        AccountSettings__c accountSettings = [SELECT Id, RegexForSendingMail__c FROM AccountSettings__c];
        
        accountSettings.RegexForSendingMail__c = '\\bTest[0-9]\\b';

        update accountSettings;

        Account account = new Account( Name     = 'Test Name',
                                       Email__c = 'test@test12323.com'  );

        //If the mock response is called it will throw an assertion error. 
        //Expectation is regex wont match name and thus no callout should be made
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(true, false));
        insert account;
        // changing the mock along with matching name
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(true, true));
        account.Name = 'Test1';
        
        Test.startTest();
        update account;
        Test.stopTest();
    }

    @IsTest
    public static void testAccountTriggerWithBlankEmail() {
        Account account = new Account(Name = 'Test Name');

        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(true, false));

        Test.startTest();
        insert account;
        Test.stopTest();

        List<Account> accountList = [SELECT Id, Name FROM Account ];
        System.assertEquals(0, accountList.size());
    }

    @IsTest
    public static void testAccountTriggerWithRegexError() {
        AccountSettings__c accountSettings = [SELECT Id, RegexForSendingMail__c FROM AccountSettings__c];
        
        accountSettings.RegexForSendingMail__c = '*';

        update accountSettings;
        Account account = new Account( Name     = 'Test Name',
                                       Email__c = 'test@test12323.com'  );

        Test.setMock(HttpCalloutMock.class, new MockHttpResponse(true, false));

        Test.startTest();
        insert account;
        Test.stopTest();

        List<Account> accountList = [SELECT Id, Name FROM Account ];
        System.assertEquals(0, accountList.size());
    }
}