force-app/main/default/objects/ExceptionLog__c/ExceptionLog__c.object-meta.xml
<CustomObject>
    <description>Object used to log any excpetions</description>
    <label>ExceptionLog</label>
    <nameField>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExcpetionLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExceptionLog__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Name of the class having error</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExceptionLog__c/fields/ExceptionDetails__c.field-meta.xml
<CustomField>
    <fullName>ExceptionDetails__c</fullName>
    <description>Exception Stack Trace</description>
    <label>Exception Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ExceptionLog__c/fields/ExceptionLine__c.field-meta.xml
<CustomField>
    <fullName>ExceptionLine__c</fullName>
    <description>Exception Line</description>
    <label>Exception Line</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExceptionLog__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <description>Exception Message</description>
    <label>Exception Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ExceptionLog__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <description>Exception Type</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExceptionLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <description>Name of the method having error</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExceptionLogger.cls
/*---------------------------------------------------------------
Description :            Class to log Exceptions 
Test Class :             AccountTriggerTest
-----------------------------------------------------------------*/
public class ExceptionLogger {
    private static List<ExceptionLog__c> exceptionLogList = new List<ExceptionLog__c>();

    // Method to insert exception to Exception Log Object
    public static void addException (Exception ex) {
        try {
            String stackTrace = ex.getStackTraceString().substringBefore('\n');
            String className  = stackTrace.substringAfter('.').substringBefore('.');	
            String methodName = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.');
            
            String exceptionLine       = ex.getLineNumber() + '';
            String exceptionStackTrace = ex.getStackTraceString();
            String exceptionType       = ex.getTypeName(); 
            String exceptionMessage    = ex.getMessage(); 

            ExceptionLog__c log = new ExceptionLog__c(
                                    ClassName__c        = className,
                                    MethodName__c       = methodName,
                                    ExceptionLine__c    = exceptionLine,
                                    ExceptionMessage__c = exceptionMessage,
                                    ExceptionDetails__c = exceptionStackTrace,
                                    ExceptionType__c    = exceptionType
                                    );

            exceptionLogList.add(log); 
        } catch (Exception e) {
            System.debug(e);
        }
    }

    public static void saveExceptionLog() {
        if(exceptionLogList.isEmpty() == false){
            Database.insert(exceptionLogList,false); 
        }
    }
 
}